spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/batch
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: spring-batch
  profiles:
    active: local
    default: local

---
spring:
  profiles:
    active: local
  datasource:
    hikari:
      url: jdbc:mysql://localhost:3306/batch
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: admin
  batch:
    jdbc:
      initialize-schema: always
    job:
#      names: ${job.name:NONE}
      enabled: true